config/urls.py
from django.urls import path, include
from django.contrib import admin

import core.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('movies', views.MovieList.as_view(),name='MovieList'),
    path('movie/<int:pk>',views.MovieDetail.as_view(),name='MovieDetail'),
]

core/models.py
from django.db import models

class Movie(models.Model):
    not_rated = 0
    rated_g = 1
    rated_pg = 2
    rated_r = 3
    ratings = (
        (not_rated, 'NR - Not Rated'),
        (rated_g, 'G - General Audiences'),
        (rated_pg, 'PG - Parental Guidance Suggested'),
        (rated_r, 'R - Restricted'),)
    title = models.CharField( max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices = ratings, default = not_rated)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)

    class Meta:
        ordering = ('-year', 'title')


    def __str__(self):
        return '{} ({})'.format(self.title, self.year)

core/views.py
from django.shortcuts import render

from django.views.generic import (
    ListView, DetailView,
)

from core.models import Movie

class MovieDetail(DetailView):
    model = Movie

class MovieList(ListView):
    paginate_by = 10
    model = Movie





# class PersonDetail(DetailView):
#     queryset = Person.objects.all_with_prefetch_movies()

core/templates/core/movie_detail.html
{% extends 'base.html' %}

 {# #}
{% block title %}
  {{ object.title }} - {{ block.super }} 
{% endblock %}

{% block main %}
<h1>{{ object }}</h1>
<p class="lead">
{{ object.plot }}
</p>
{% endblock %}

{% block sidebar %}
<div>
This movie is rated:
  <span class="badge badge-primary">
  {{ object.get_rating_display }}
  </span>
</div>
{% endblock %}

core/templates/core/movie_list.html
{% extends 'base.html' %}


{% block title %}
All the Movies
{% endblock %}

{% block main %}
<ul>
  {% for movie in object_list %}
    <li>
      <a href="{% url 'core:MovieDetail' pk=movie.id %}">
        {{ movie }}
      </a>
    </li>
  {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" >
<head >
  <meta charset="UTF-8" >
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  >
  <link
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    rel="stylesheet"
    crossorigin="anonymous"
  >
  <title >
    {% block title %}MyMDB{% endblock %}
  </title>
  <style>
    .mymdb-masthead {
      background-color: #EEEEEE;
      margin-bottom: 1em;
    }
  </style>

</head >
<body >
<div class="mymdb-masthead">
  <div class="container">
    <nav class="nav">
      <div class="navbar-brand">MyMDB</div>
      <a
        class="nav-link"
        href="{% url 'core:MovieList' %}"
      >
        Movies
      </a>
    </nav>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-8 mymdb-main">
     {% block main %}{% endblock %}
    </div>
    <div
        class="col-sm-3 offset-sm-1 mymdb-sidebar">
      {% block sidebar %}{% endblock %}
    </div>
  </div>
</div>

</body >
</html >